### ISSUE TITLE
集成后 h5 上传图片异常

### ISSUE THREAD

**Issue by tomisacatyet** [runner525/x5webview-cordova-plugin#3]
07-13 15:51:35.657 31021-31021/com.ionicframework.starter W/System.err: java.lang.ClassNotFoundException: com.android.webview.chromium.FileChooserParamsAdapter
07-13 15:51:35.658 31021-31021/com.ionicframework.starter W/System.err:     at java.lang.Class.classForName(Native Method)
07-13 15:51:35.658 31021-31021/com.ionicframework.starter W/System.err:     at java.lang.Class.forName(Class.java:317)
07-13 15:51:35.658 31021-31021/com.ionicframework.starter W/System.err:     at java.lang.Class.forName(Class.java:275)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at com.tencent.smtt.sdk.WebChromeClient$FileChooserParams.parseResult(Unknown Source)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at org.apache.cordova.x5engine.X5WebChromeClient$5.onActivityResult(X5WebChromeClient.java:257)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:151)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:348)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6319)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4006)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4053)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:185)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at android.os.Looper.loop(Looper.java:194)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5847)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.webview.chromium.FileChooserParamsAdapter" on path: DexPathList[[zip file "/data/app/com.ionicframework.starter-2/base.apk"],nativeLibraryDirectories=[/data/app/com.ionicframework.starter-2/lib/arm, /vendor/lib, /system/lib]]
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err: 	... 19 more
07-13 15:51:35.659 31021-31021/com.ionicframework.starter W/System.err: 	Suppressed: java.lang.ClassNotFoundException: com.android.webview.chromium.FileChooserParamsAdapter
07-13 15:51:35.660 31021-31021/com.ionicframework.starter W/System.err:     at java.lang.Class.classForName(Native Method)
07-13 15:51:35.660 31021-31021/com.ionicframework.starter W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-13 15:51:35.660 31021-31021/com.ionicframework.starter W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-13 15:51:35.660 31021-31021/com.ionicframework.starter W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-13 15:51:35.660 31021-31021/com.ionicframework.starter W/System.err: 		... 20 more
07-13 15:51:35.660 31021-31021/com.ionicframework.starter W/System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
07-13 15:51:47.589 31021-31044/com.ionicframework.starter I/System.out: [CDS]close[49702]

**Comment by runner525** [comment]
这是x5内核在无法加载的情况下切换到系统内核时的一个BUG, 后续会更新修复这个问题.

没有能正常加载x5内核的问题可以使用这个工具检测一下:http://bbs.mb.qq.com/thread-1944983-1-1.html

感谢您的反馈!!
