### ISSUE TITLE
打包成APK后, 第一次运行正常, 第二次就不能运行了.

### ISSUE THREAD

**Issue by finscn** [runner525/x5webview-cordova-plugin#7]
界面提示信息如图:
<img width="471" alt="2017-08-20 5 14 19" src="https://user-images.githubusercontent.com/288367/29490169-8bfbe8b4-84f9-11e7-9d33-371b975cba22.png">

我使用了 cordova-plugin-crypt-file 这个插件. 

相关问题我曾经在  http://bbs.mb.qq.com/thread-1594137-1-1.html 里陈述过.

**Comment by finscn** [comment]
我试了下 之前用的另一个好用的 cordova-x5  插件, 也不行. 现象一样.
我估计问题可能出在  tbs 的 sdk(就是那个jar) 里的内容 对 新版本的 cordova (7.0.1)  支持有点问题.

**Comment by finscn** [comment]
我用chrome 远程调试了一下, 发现一个奇怪的现象.

第一次能运行时, UA是:
Mozilla/5.0 (Linux; Android 7.0; SM-G9300 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043502 Safari/537.36

第二次再启动App, UA就变成了:
Mozilla/5.0 (Linux; Android 7.0; SM-G9300 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Mobile Safari/537.36

tbs没有被加载

**Comment by finscn** [comment]
第二次启动时, 发现了这些错误信息:
```
08-20 23:13:03.283  9796  9796 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getDir(java.lang.String, int)' on a null object reference
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.s.q(Unknown Source)
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.s.<init>(Unknown Source)
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.s.a(Unknown Source)
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.TbsSDKExtension.c(Unknown Source)
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.TbsSDKExtension.<init>(Unknown Source)
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.TbsSDKExtension.<init>(Unknown Source)
08-20 23:13:03.285  9796  9796 W System.err: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-20 23:13:03.285  9796  9796 W System.err: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.smtt.sdk.QbSdk.b(Unknown Source)
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.smtt.sdk.QbSdk.a(Unknown Source)
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.smtt.sdk.QbSdk.a(Unknown Source)
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.smtt.sdk.TbsShareManager.findCoreForThirdPartyApp(Unknown Source)
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.smtt.sdk.TbsShareManager.h(Unknown Source)
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.smtt.sdk.QbSdk.a(Unknown Source)
08-20 23:13:03.285  9796  9796 W System.err: 	at com.tencent.smtt.sdk.q.a(Unknown Source)
08-20 23:13:03.286  9796  9796 W System.err: 	at com.tencent.smtt.sdk.bo.a(Unknown Source)
08-20 23:13:03.286  9796  9796 W System.err: 	at com.tencent.smtt.sdk.WebView.a(Unknown Source)
08-20 23:13:03.286  9796  9796 W System.err: 	at com.tencent.smtt.sdk.WebView.<init>(Unknown Source)
08-20 23:13:03.286  9796  9796 W System.err: 	at com.tencent.smtt.sdk.WebView.<init>(Unknown Source)
08-20 23:13:03.286  9796  9796 W System.err: 	at com.tencent.smtt.sdk.WebView.<init>(Unknown Source)
08-20 23:13:03.286  9796  9796 W System.err: 	at com.tencent.smtt.sdk.WebView.<init>(Unknown Source)
08-20 23:13:03.286  9796  9796 W System.err: 	at org.apache.cordova.x5engine.X5WebView.<init>(X5WebView.java:45)
08-20 23:13:03.286  9796  9796 W System.err: 	at org.apache.cordova.x5engine.X5WebView.<init>(X5WebView.java:41)
08-20 23:13:03.286  9796  9796 W System.err: 	at org.apache.cordova.x5engine.X5WebViewEngine.<init>(X5WebViewEngine.java:77)
08-20 23:13:03.286  9796  9796 W System.err: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-20 23:13:03.286  9796  9796 W System.err: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
08-20 23:13:03.286  9796  9796 W System.err: 	at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:79)
08-20 23:13:03.286  9796  9796 W System.err: 	at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:206)
08-20 23:13:03.286  9796  9796 W System.err: 	at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:202)
08-20 23:13:03.286  9796  9796 W System.err: 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:146)
08-20 23:13:03.286  9796  9796 W System.err: 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
08-20 23:13:03.286  9796  9796 W System.err: 	at cn.fattyboy.flukes.MainActivity.onCreate(MainActivity.java:39)
08-20 23:13:03.287  9796  9796 W System.err: 	at android.app.Activity.performCreate(Activity.java:6912)
08-20 23:13:03.287  9796  9796 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
08-20 23:13:03.287  9796  9796 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2870)
08-20 23:13:03.287  9796  9796 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2978)
08-20 23:13:03.287  9796  9796 W System.err: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
08-20 23:13:03.287  9796  9796 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
08-20 23:13:03.287  9796  9796 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-20 23:13:03.287  9796  9796 W System.err: 	at android.os.Looper.loop(Looper.java:154)
08-20 23:13:03.287  9796  9796 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6646)
08-20 23:13:03.287  9796  9796 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-20 23:13:03.287  9796  9796 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
08-20 23:13:03.287  9796  9796 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
08-20 23:13:03.290  9796  9796 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getDir(java.lang.String, int)' on a null object reference
08-20 23:13:03.290  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.s.o(Unknown Source)
08-20 23:13:03.290  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.s.q(Unknown Source)
08-20 23:13:03.290  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.s.<init>(Unknown Source)
08-20 23:13:03.290  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.s.a(Unknown Source)
08-20 23:13:03.290  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.TbsSDKExtension.c(Unknown Source)
08-20 23:13:03.290  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.TbsSDKExtension.<init>(Unknown Source)
08-20 23:13:03.290  9796  9796 W System.err: 	at com.tencent.tbs.sdk.extension.TbsSDKExtension.<init>(Unknown Source)
08-20 23:13:03.290  9796  9796 W System.err: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-20 23:13:03.290  9796  9796 W System.err: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
08-20 23:13:03.290  9796  9796 W System.err: 	at com.tencent.smtt.sdk.QbSdk.b(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at com.tencent.smtt.sdk.QbSdk.a(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at com.tencent.smtt.sdk.QbSdk.a(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at com.tencent.smtt.sdk.TbsShareManager.findCoreForThirdPartyApp(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at com.tencent.smtt.sdk.TbsShareManager.h(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at com.tencent.smtt.sdk.QbSdk.a(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at com.tencent.smtt.sdk.q.a(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at com.tencent.smtt.sdk.bo.a(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at com.tencent.smtt.sdk.WebView.a(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at com.tencent.smtt.sdk.WebView.<init>(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at com.tencent.smtt.sdk.WebView.<init>(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at com.tencent.smtt.sdk.WebView.<init>(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at com.tencent.smtt.sdk.WebView.<init>(Unknown Source)
08-20 23:13:03.291  9796  9796 W System.err: 	at org.apache.cordova.x5engine.X5WebView.<init>(X5WebView.java:45)
08-20 23:13:03.291  9796  9796 W System.err: 	at org.apache.cordova.x5engine.X5WebView.<init>(X5WebView.java:41)
08-20 23:13:03.291  9796  9796 W System.err: 	at org.apache.cordova.x5engine.X5WebViewEngine.<init>(X5WebViewEngine.java:77)
08-20 23:13:03.291  9796  9796 W System.err: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-20 23:13:03.291  9796  9796 W System.err: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
08-20 23:13:03.291  9796  9796 W System.err: 	at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:79)
08-20 23:13:03.291  9796  9796 W System.err: 	at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:206)
08-20 23:13:03.291  9796  9796 W System.err: 	at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:202)
08-20 23:13:03.291  9796  9796 W System.err: 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:146)
08-20 23:13:03.291  9796  9796 W System.err: 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
08-20 23:13:03.292  9796  9796 W System.err: 	at cn.fattyboy.flukes.MainActivity.onCreate(MainActivity.java:39)
08-20 23:13:03.292  9796  9796 W System.err: 	at android.app.Activity.performCreate(Activity.java:6912)
08-20 23:13:03.292  9796  9796 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
08-20 23:13:03.292  9796  9796 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2870)
08-20 23:13:03.292  9796  9796 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2978)
08-20 23:13:03.292  9796  9796 W System.err: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
08-20 23:13:03.292  9796  9796 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
08-20 23:13:03.292  9796  9796 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-20 23:13:03.292  9796  9796 W System.err: 	at android.os.Looper.loop(Looper.java:154)
08-20 23:13:03.292  9796  9796 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6646)
08-20 23:13:03.292  9796  9796 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-20 23:13:03.292  9796  9796 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
08-20 23:13:03.292  9796  9796 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
08-20 23:13:03.295  9796  9796 W linker  : Warning: "/data/data/com.tencent.mm/app_tbs/core_share/tbs_sdk_extension_dex.jar" is not a directory (excluding from path)
```

**Comment by finscn** [comment]
x5 论坛里有人反应过类似问题  http://bbs.mb.qq.com/thread-1944166-1-1.html

**Comment by finscn** [comment]
问题解决了, 方案在这里 

http://bbs.mb.qq.com/thread-1944166-2-1.html#2158471

**Comment by Wang-Zoo** [comment]
@finscn  遇到了同样的问题，请问你现在解决了吗？

**Comment by Torchwoods** [comment]
问题解决了吗？

**Comment by ColdStarasd** [comment]
这个怎么解决的呢？
