### ISSUE TITLE
说实话这个插件写得如此烂

### ISSUE THREAD

**Issue by leeh123** [runner525/x5webview-cordova-plugin#8]
最简单的测试，都不能通过，也是醉了

5 D/OpenSSLLib: OpensslErr:Module:12(116:176); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:186;Function:ASN1_get_object
08-21 15:42:12.765 4078-4570/com.cordova.x5 D/OpenSSLLib: OpensslErr:Module:12(116:176); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:186;Function:ASN1_get_object
08-21 15:42:15.592 4078-4078/com.cordova.x5 D/X5WebChromeClient: file:///android_asset/www/cordova.js: Line 1223 : deviceready has not fired after 5 seconds.
08-21 15:42:15.593 4078-4078/com.cordova.x5 I/chromium: [INFO:CONSOLE(1223)] "deviceready has not fired after 5 seconds.", source: file:///android_asset/www/cordova.js (1223)
08-21 15:42:15.595 4078-4078/com.cordova.x5 D/X5WebChromeClient: file:///android_asset/www/cordova.js: Line 1216 : Channel not fired: onFileSystemPathsReady
08-21 15:42:15.595 4078-4078/com.cordova.x5 I/chromium: [INFO:CONSOLE(1216)] "Channel not fired: onFileSystemPathsReady", source: file:///android_asset/www/cordova.js (1216)
08-21 15:42:16.148 4078-4570/com.cordova.x5 I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
08-21 15:42:16.148 4078-4570/com.cordova.x5 D/libc-netbsd: [getaddrinfo]: hostname=182.247.229.161; servname=(null); netid=0; mark=0
08-21 15:42:16.148 4078-4570/com.cordova.x5 D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
08-21 15:42:28.470 4078-4325/com.cordova.x5 W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getDir(java.lang.String, int)' on a null object reference
08-21 15:42:28.470 4078-4325/com.cordova.x5 W/System.err:     at com.tencent.tbs.sdk.extension.s.o(Unknown Source)
08-21 15:42:28.471 4078-4325/com.cordova.x5 W/System.err:     at com.tencent.tbs.sdk.extension.TbsSDKExtension.b(Unknown Source)
08-21 15:42:28.471 4078-4325/com.cordova.x5 W/System.err:     at com.tencent.tbs.sdk.extension.TbsSDKExtension.a(Unknown Source)
08-21 15:42:28.471 4078-4325/com.cordova.x5 W/System.err:     at com.tencent.tbs.sdk.extension.n.run(Unknown Source)
08-21 15:42:28.471 4078-4325/com.cordova.x5 W/System.err:     at java.util.Timer$TimerImpl.run(Timer.java:284)

操作步骤很简单，执行这几个命令，然后打包出apk出来运行就这些错误了。
cordova create testx5 com.cordova.x5 testx5;
cd testx5/;
cordova platform add android;
cordova plugin add https://github.com/runner525/x5webview-cordova-plugin.git;
cordova plugin add cordova-plugin-file-transfer;
cordova plugin add cordova-plugin-inappbrowser;
cordova plugin add cordova-open
其他一切都是默认的，然后在启动那块就一直显示connecting  to device。还有一堆的异常输出什么的。

**Comment by likyh** [comment]
https://github.com/runner525/x5webview-cordova-plugin/issues/24
看我的解决方案
